### ISSUE TITLE
Dealing with parentheses in doi

### ISSUE THREAD

**Issue by ChayaSt** [manubot/manubot#133]
When I add a doi that has parentheses, anything after the first parenthesis is ignored, even when I escape with `\`. 

Example:
`build.sh` generates the following error when the content contains either of these doi
`[@doi:10.1016/0009-2614(84)85645-6]`  or `[@doi:10.1016/0009-2614\(84\)85645-6]` 
```
## ERROR
Citeproc retrieval failure for doi:10.1016/0009-2614
Traceback (most recent call last):
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/site-packages/manubot/process/util.py", line 277, in generate_csl_items
    citeproc = citation_to_citeproc(standard_id)
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/util.py", line 266, in citation_to_citeproc
    csl_item = citeproc_retriever(identifier)
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/doi.py", line 78, in get_doi_citeproc
    raise error
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/doi.py", line 74, in get_doi_citeproc
    citeproc = response.json()
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/sternc1/anaconda3/envs/manubot/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dhimmel** [comment]
Yes, this an annoying. Currently, we recommend the following alternatives in the [usage docs](https://github.com/manubot/rootstock/blob/bc094bd3d6cec6935298b4acf50e45ad55bf45c8/USAGE.md):

1. use a shortDOI like `[@doi:10/bdfk5f]`
2. use a citation tag like `[@tag:natiello]` where the tag points to `@doi:10.1016/0009-2614(84)85645-6` in `citation-tags.tsv`.

Will think about how we can improve the user experience in these situations, but we're a bit constrained by not wanting to deviate too much from Pandoc's citation key syntax.

**Comment by ChayaSt** [comment]
Thanks! 

And sorry, I did not notice that in the usage docs - my bad.

**Comment by dhimmel** [comment]
No worries... we're still working on making the usage docs more accessible. And issues like this help us know what actually is taking up our user's time, so they are still useful! Best of luck
