### ISSUE TITLE
Equation breaking markdown read

### ISSUE THREAD

**Issue by aarmey** [manubot/manubot#217]
Something about this equation:

`$$v_{\mathbf{q},eq} = \binom{f}{\mathbf{q}} \frac{L_0}{K_x^* } \prod_{i=1\\ j=0}^{i=N_L\\ j=N_R}{{φ_{ij}}^{q_{ij}}},$$`

Gives the following exception:

```
Traceback (most recent call last):
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/bin/manubot", line 8, in <module>
    sys.exit(main())
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/manubot/command.py", line 228, in main
    function(args)
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/manubot/process/process_command.py", line 34, in cli_process
    prepare_manuscript(args)
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/manubot/process/util.py", line 518, in prepare_manuscript
    text = template_with_jinja2(text, variables)
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/manubot/process/util.py", line 491, in template_with_jinja2
    template = jinja_environment.from_string(text)
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/jenkins/workspace/eyer-lab_FcgR.jl_manuscript_text/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 114, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '{'
```

The equation works normally in Pandoc and latex.

**Comment by dhimmel** [comment]
Ah, jinja2 is running on this file prior to when it gets interpreted as an equation.

Can you wrap the equation in a [jinja2 raw block](https://jinja.palletsprojects.com/en/2.11.x/templates/#escaping):

```
{% raw %}
$$v_{\mathbf{q},eq} = \binom{f}{\mathbf{q}} \frac{L_0}{K_x^* } \prod_{i=1\\ j=0}^{i=N_L\\ j=N_R}{{φ_{ij}}^{q_{ij}}},$$
{% endraw %}
```

**Comment by dhimmel** [comment]
This is the first time I've seen this issue, but it can happen whenever `{{` or `}}` occurs for some other reason than jinja2 templating.

Something I'll keep in mind when evaluating upgrades to our template system in the future.

**Comment by aarmey** [comment]
That fixed it. Thanks!

**Comment by phiresky** [comment]
Just encountered the same issue (https://github.com/manubot/rootstock/issues/431), might be good if the error message could be improved? Or alternatively, do some other fix such as disabling templating in equations or making everything "raw" by default and making a escape sequence to allow template syntax when intentional
