### ISSUE TITLE
Bad error message for failing arxiv citation

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#278]
Am getting the following stderr for `manubot cite arxiv:1607.00653 --log-level=INFO`:

```python-traceback
## WARNING
Generating csl_item for 'arxiv:1607.00653' failed due to a ValueError:
not enough values to unpack (expected 1, got 0)
## INFO
not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/home/dhimmel/Documents/repos/manubot/manubot/cite/citekey.py", line 268, in citekey_to_csl_item
    csl_item = citekey.csl_item
  File "/home/dhimmel/miniconda3/envs/manubot-dev/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/dhimmel/Documents/repos/manubot/manubot/cite/citekey.py", line 211, in csl_item
    csl_item = self.handler.get_csl_item(self)
  File "/home/dhimmel/Documents/repos/manubot/manubot/cite/arxiv.py", line 30, in get_csl_item
    return get_arxiv_csl_item(citekey.standard_accession)
  File "/home/dhimmel/Documents/repos/manubot/manubot/cite/arxiv.py", line 77, in get_arxiv_csl_item
    return get_arxiv_csl_item_oai(arxiv_id)
  File "/home/dhimmel/Documents/repos/manubot/manubot/cite/arxiv.py", line 181, in get_arxiv_csl_item_oai
    (header_elem,) = xml_tree.findall(
ValueError: not enough values to unpack (expected 1, got 0)
```

Not sure why the arxiv metadata lookup is failing, and the stderr doesn't contain the actual arxiv XML that is bad.

**Comment by dhimmel** [comment]
https://export.arxiv.org/oai2?verb=GetRecord&metadataPrefix=arXiv&identifier=oai%3AarXiv.org%3A1607.00653 returns:

> Retry after 600 seconds
> The arXiv OAI service is unavailable due to maintenance

**Comment by dhimmel** [comment]
Adding response.raise_for_status() throws an HTTPError with a much better message:

```
## WARNING
Generating csl_item for 'arxiv:1607.00653' failed due to a HTTPError:
503 Server Error: Retry after specified interval for url: https://export.arxiv.org/oai2?verb=GetRecord&metadataPrefix=arXiv&identifier=oai%3AarXiv.org%3A1607.00653
```
