### ISSUE TITLE
ai-revision not available when installing via pip

### ISSUE THREAD

**Issue by Prof-ThiagoOliveira** [manubot/manubot#362]
Dear maintainers, I am trying to install Manubot to access the ai-revision. However, when installing it via pip as recommended on the README page (pip install --upgrade manubot), I only can access process, cite and webpage. Is there any reason for that?

![Screenshot from 2023-02-03 10-15-51](https://user-images.githubusercontent.com/34395021/216606495-8998c5fb-c0e7-48f2-a4ce-461c228a27f5.png)

Extra info:

* Linux shark 5.15.0-58-generic 64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* pandoc:   Installed: 3.0.1-1

Best regards, 
Thiago

**Comment by dhimmel** [comment]
We haven't created a release with d4242ffa4194e4a13a68c5f6466feff559d3f9d5 yet. You can see that by going to the commit on GH and seeing that there are no tags with the commit yet:

> ![image](https://user-images.githubusercontent.com/1117703/216611936-4441c6ac-2cfd-4574-a80c-4a6dd404569e.png)

I can create the release today. @miltondp was there anything other changes on the Manubot side needed before release?

**Comment by dhimmel** [comment]
@Prof-ThiagoOliveira you can also do the following in the meantime (install by commit rather than PyPI release):

```sh
pip install git+https://github.com/manubot/manubot@d4242ffa4194e4a13a68c5f6466feff559d3f9d5#egg=manubot[ai-rev]
```

**Comment by dhimmel** [comment]
Also noting the corresponding rootstock change which is still in progress (but hopefully merged soon) at https://github.com/manubot/rootstock/pull/484

**Comment by miltondp** [comment]
> I can create the release today. @miltondp was there anything other changes on the Manubot side needed before release?

Nop, no more changes in Manubot are needed.

**Comment by dhimmel** [comment]
Manubot v0.5.6 is [released](https://github.com/manubot/manubot/releases/tag/v0.5.6) and available on [PyPI](https://pypi.org/project/manubot/0.5.6/), so `pip install manubot` will now give you the ai-revision subcommand.

**Comment by miltondp** [comment]
Actually, you need to install the extra component `ai-rev`: `pip install manubot[ai-rev]`. Otherwise, it will give an error:

```bash
Traceback (most recent call last):
  File "/home/miltondp/software/miniconda3/envs/test/bin/manubot", line 8, in <module>
    sys.exit(main())
  File "/home/miltondp/software/miniconda3/envs/test/lib/python3.10/site-packages/manubot/command.py", line 302, in main
    function(args)
  File "/home/miltondp/software/miniconda3/envs/test/lib/python3.10/site-packages/manubot/ai_revision/ai_revision_command.py", line 8, in cli_process
    from manubot_ai_editor import models
ModuleNotFoundError: No module named 'manubot_ai_editor'
```

Maybe in the future, we should disable the subcommand `ai-revision` if the `ai-rev` was not installed.

**Comment by dhimmel** [comment]
Maybe in the future, we should disable the subcommand ai-revision if the ai-rev was not installed.

I think it's better to keep the command but raise an Exception. The current exception is okay, perhaps could be improved with something a message like: "install manubot with the ai-rev extras"

**Comment by miltondp** [comment]
> perhaps could be improved with something a message like: "install manubot with the ai-rev extras"

I opened a PR with this change [here](https://github.com/manubot/manubot/pull/363).
